services:
  Dbp\Relay\MonoConnectorGenericBundle\Service\GenericService:
    autowire: true
    autoconfigure: true
    public: true
    tags:
      - { name: monolog.logger, channel: 'dbp_relay_mono_audit' }
